apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-api-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: payment-api.4.187.130.156.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: payment-api-service
            port:
              number: 80
